### PR TITLE
Fixes Setup Ruby action step

### PR DESCRIPTION
**Pull request by juanpedromoreno**
Thanks @alejandrohdezma for the hint.

### CODE REVIEW

**Comment by sloshy** [comment]
@juanpedromoreno I'm interested in what exactly this fixes. Is there a failing build somewhere that needs this? Is this a fix that would need to be applied to other repositories (not just ours, for example) that are setting up ruby? Thanks in advance.

**Comment by juanpedromoreno** [comment]
Hey @sloshy , yeah, basically we are currently experiencing this issue for all the repos: https://github.com/47degrees/.github/runs/1838738471?check_suite_focus=true#step:15:10

@alejandrohdezma pointed me out that the job might be looking for the `.ruby-version` file in the wrong place, instead of where the script is running.

Said that the current changes are not valid either. I'm submitting new commits soon.

**Comment by sloshy** [comment]
I think the issue is, it can't detect a symlink. The `.ruby-version` in this repo is symlinked with the one that it sends to all the other repos, and those repos are working fine on their own, just not this one. Maybe set the working directory to `root-files` for this step? I don't think `main` will work, as there is no directory named `main`.

**Comment by juanpedromoreno** [comment]
Yeah, I'm not sure, but for that job, the main directory is created [here](https://github.com/47degrees/.github/blob/master/.github/workflows/auto-update.yml#L91)

**Review by alejandrohdezma — APPROVED** [review]

**Comment by juanpedromoreno** [comment]
Let's merge and test 🤞

**Comment by sloshy** [comment]
Ahh ok excuse my lack of familiarity with the bot. My bad.

**Comment by juanpedromoreno** [comment]
No problem, thanks for your comments!

**Pull request merged**
